import type { Portfolio } from "./types";

// Starter content. Shown when no database is configured, and loadable into
// MongoDB from the admin dashboard. Replace everything from /admin.
export const seed: Portfolio = {
  profile: {
    name: "Mohiuddin Mehedi",
    headline: "Full Stack Developer",
    roles: ["Full Stack Developer", "Next.js Engineer", "Node.js & API Architect", "Researcher"],
    intro:
      "I design and build fast, reliable web products end to end, from database schema and APIs to polished, accessible interfaces.",
    about:
      "I'm a full stack developer who enjoys turning messy problems into simple, well-engineered software. I work across the stack with TypeScript, React, Next.js, Node.js and both SQL and NoSQL databases, and I care about performance, clean architecture and developer experience.\n\nAlongside industry work I contribute to research, which keeps me rigorous about measuring what matters and writing things down clearly.",
    location: "Washington DC, USA",
    email: "info@mmehedi.me",
    available: true,
    availabilityText: "Open to full-time roles & freelance projects",
    avatarUrl: "",
    resumeUrl: "/resume.pdf",
    socials: {
      github: "https://github.com/aroien",
      linkedin: "https://www.linkedin.com/in/momehedi/",
      scholar: "",
      orcid: "",
      researchgate: "",
      twitter: "",
    },
    stats: [
      { value: "4+", label: "Years experience" },
      { value: "15+", label: "Projects shipped" },
      { value: "2", label: "Research papers" },
      { value: "10+", label: "Happy clients" },
    ],
    skills: [
      { category: "Frontend", items: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Redux Toolkit", "Framer Motion"] },
      { category: "Backend", items: ["Node.js", "Express", "NestJS", "REST APIs", "GraphQL", "Auth & JWT"] },
      { category: "Databases", items: ["PostgreSQL", "MongoDB", "Prisma", "Mongoose", "Redis"] },
      { category: "DevOps & Tools", items: ["Docker", "Vercel", "AWS", "GitHub Actions", "Git", "Figma"] },
    ],
  },
  projects: [
    {
      id: "seed-p1",
      title: "IGRS Learning Platform",
      description:
        "A full-stack e-learning platform with course management, assignments, coupons, notifications and student progress tracking. Built with Next.js and TypeScript and running in production.",
      category: "Full Stack",
      year: "2025",
      tech: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind CSS"],
      imageUrl: "",
      liveUrl: "https://igrsbd.org",
      repoUrl: "",
      featured: true,
      order: 0,
    },
    {
      id: "seed-p2",
      title: "E-Commerce Platform",
      description:
        "Online store with product catalog, cart, secure Stripe checkout and an admin dashboard for inventory and order management.",
      category: "Full Stack",
      year: "2024",
      tech: ["React", "Redux Toolkit", "Node.js", "MongoDB", "Stripe"],
      imageUrl: "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&h=800&fit=crop",
      liveUrl: "",
      repoUrl: "https://github.com/aroien",
      featured: true,
      order: 1,
    },
    {
      id: "seed-p3",
      title: "Weather Dashboard",
      description:
        "Geolocation-based forecasts with a 7-day outlook and animated data visualizations.",
      category: "Frontend",
      year: "2023",
      tech: ["React", "OpenWeather API", "Chart.js"],
      imageUrl: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=1200&h=800&fit=crop",
      liveUrl: "",
      repoUrl: "https://github.com/aroien",
      featured: false,
      order: 2,
    },
    {
      id: "seed-p4",
      title: "Social Media Analytics",
      description:
        "Real-time analytics dashboard aggregating social metrics with interactive D3.js charts and CSV export.",
      category: "Full Stack",
      year: "2023",
      tech: ["React", "D3.js", "Node.js", "REST API"],
      imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop",
      liveUrl: "",
      repoUrl: "https://github.com/aroien",
      featured: false,
      order: 3,
    },
  ],
  experience: [
    {
      id: "seed-e1",
      role: "Full Stack Developer",
      company: "Your Current Company",
      companyUrl: "",
      location: "Remote",
      employmentType: "Full-time",
      startDate: "2024-01",
      endDate: "",
      summary: "Sample entry: replace it from the admin panel.",
      highlights: [
        "Built and shipped a Next.js + PostgreSQL platform used by thousands of students",
        "Designed REST APIs and role-based auth for admin, instructor and student roles",
        "Cut page load times by 40% through caching and image optimization",
      ],
      tech: ["Next.js", "TypeScript", "PostgreSQL", "Prisma"],
      order: 0,
    },
    {
      id: "seed-e2",
      role: "Frontend Developer",
      company: "Previous Company",
      companyUrl: "",
      location: "Dhaka, Bangladesh",
      employmentType: "Full-time",
      startDate: "2022-03",
      endDate: "2023-12",
      summary: "Sample entry: replace it from the admin panel.",
      highlights: [
        "Implemented responsive, accessible UIs from Figma designs",
        "Introduced TypeScript and component testing across the codebase",
      ],
      tech: ["React", "Redux", "Tailwind CSS"],
      order: 1,
    },
  ],
  publications: [
    {
      id: "seed-r1",
      title: "Sample Paper Title: Replace From the Admin Panel",
      authors: "Mohiuddin Mehedi, Co-Author One, Co-Author Two",
      venue: "International Conference on Example Research",
      year: "2025",
      type: "Conference",
      status: "Published",
      abstract:
        "This is placeholder text for the abstract. Log in to /admin and edit this entry with your paper's real details, links and DOI.",
      url: "",
      pdfUrl: "",
      doi: "",
      codeUrl: "",
      featured: true,
      order: 0,
    },
    {
      id: "seed-r2",
      title: "Another Sample Publication",
      authors: "Co-Author One, Mohiuddin Mehedi",
      venue: "Journal of Example Studies",
      year: "2024",
      type: "Journal",
      status: "Under Review",
      abstract: "Placeholder abstract.",
      url: "",
      pdfUrl: "",
      doi: "",
      codeUrl: "",
      featured: false,
      order: 1,
    },
  ],
};
